apiVersion: v1
kind: Pod
metadata:
  name: user-service-pod
  labels:
    name: user
spec:
  containers:
  - name: user-service
    image: gandie/ecommerce-user-service   
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9008
